services:
  il-news-mcp:
    build: .
    restart: unless-stopped
    ports:
      - 8880:8880
    entrypoint: ["/main", "-host=0.0.0.0", "-port=8880"]

  mcp-inspect:
    image: ghcr.io/modelcontextprotocol/inspector:latest
    environment:
      HOST: 0.0.0.0
    ports:
      - 6274:6274
      - 6277:6277
    depends_on:
      - il-news-mcp
