version: "3"

tasks:
  tidy:
    cmds:
      - go mod tidy
  vet:
    cmds:
      - go vet ./...
  fix:
    cmds:
      - go fix ./...
  test:
    cmds:
      - go test -v {{default "./..." .TEST_DIR}}
  watch:
    cmds:
      - air
